// <auto-generated />
using System;
using LlanoApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LlanoApp.Infrastructure.Migrations
{
    [DbContext(typeof(LlanoAppDbContext))]
    [Migration("20240731204750_AddResourceState")]
    partial class AddResourceState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.MessageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourcesId");

                    b.ToTable("MessageHistories");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceStatesId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourceStatesId");

                    b.HasIndex("ResourceTypesId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ResourceStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6475),
                            State = "required",
                            UpdateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6474)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6478),
                            State = "Discarded",
                            UpdateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6477)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6479),
                            State = "Refused",
                            UpdateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6479)
                        });
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6360),
                            TypeName = "Leyenda",
                            UpdateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6349)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6364),
                            TypeName = "Palabras",
                            UpdateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6364)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6366),
                            TypeName = "Coplas",
                            UpdateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6366)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6368),
                            TypeName = "Refranes",
                            UpdateDate = new DateTime(2024, 7, 31, 15, 47, 49, 806, DateTimeKind.Local).AddTicks(6367)
                        });
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.MessageHistory", b =>
                {
                    b.HasOne("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", "Resources")
                        .WithMany("MessageHistory")
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", b =>
                {
                    b.HasOne("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceState", "ResourceStates")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceStatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceType", "ResourceTypes")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceStates");

                    b.Navigation("ResourceTypes");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", b =>
                {
                    b.Navigation("MessageHistory");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceState", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
