// <auto-generated />
using System;
using LlanoApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LlanoApp.Infrastructure.Migrations
{
    [DbContext(typeof(LlanoAppDbContext))]
    partial class LlanoAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.MessageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourcesId");

                    b.ToTable("MessageHistories");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceStatesId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourceStatesId");

                    b.HasIndex("ResourceTypesId");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceStates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ResourceStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5384),
                            NameState = "Solicitado",
                            UpdateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5384)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5386),
                            NameState = "Descartado",
                            UpdateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5386)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5387),
                            NameState = "Aprobado",
                            UpdateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5387)
                        });
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5277),
                            TypeName = "Leyenda",
                            UpdateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5263)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5280),
                            TypeName = "Palabra",
                            UpdateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5279)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5281),
                            TypeName = "Copla",
                            UpdateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5281)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5282),
                            TypeName = "Refran",
                            UpdateDate = new DateTime(2024, 8, 14, 8, 47, 23, 270, DateTimeKind.Local).AddTicks(5282)
                        });
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.MessageHistory", b =>
                {
                    b.HasOne("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", "Resources")
                        .WithMany("MessageHistory")
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", b =>
                {
                    b.HasOne("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceStates", "ResourceStates")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceStatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceTypes", "ResourceTypes")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceStates");

                    b.Navigation("ResourceTypes");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.Resource", b =>
                {
                    b.Navigation("MessageHistory");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceStates", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("LlanoApp.Domain.AggregateModel.ResourceAggregate.ResourceTypes", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
